
title: SLOTH
email: shaden@cs.umn.edu
description: The Surprisingly Large Open Tensor Hub
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ShadenSmith

# Build settings
markdown: kramdown
#theme: minima
theme: beautiful-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  tensors:
    output: true
    permalink: /tensors/:path/


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tensors"
    values:
      layout: "tensor_layout"

navbar-links:
  about: "about"
  tensors: "tensors"
  contributing: "contributing"

rss: false
