
title: FROSTT
description: The Formidable Repository of Open Sparse Tensors and Tools
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
#theme: minima
theme: beautiful-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  tensors:
    output: true
    permalink: /tensors/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tensors"
    values:
      layout: "tensor_layout"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      comments: false
      social-share: false

navbar-links:
  about: "about"
  news: "news"
  tensors:
    - collection: "tensors/index.html"
    - file formats: "tensors/file-formats"
  tools:
    - splatt: "http://shaden.io/splatt.html"
  contributing: "contributing"

rss: false

author:
  name: Shaden Smith
  email: shaden@cs.umn.edu
  github: ShadenSmith

